keys:
  - &users
    - &dev age1ludke0yn29dzdrt6xtq6jnphpzdat0p7tg86muftauv4d9z5kqwsv4n7cr
    - &joshk age1mufyq6qccz0r0czyg575vkx6a03exdfpj767fg7nl2r2jtgk5c2q567q50
  - &hosts
    - &server age1ap6gwsfj5hx6p4k8kjavu2ad30kn5rrmsgeze5camjz9cxrrqswsy3wnx0
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *dev
          - *joshk
          - *server