{ config, ... }:
''
  @import "../../.cache/wal/colors-waybar.css";
  /* colors-waybar.css is generated by pywal, and contains the colors of the current theme the available variables are:
      @background,
      @foreground, 
      @cursor, 
      @color0,
      @color1,
      @color2,
      @color3,
      @color4,
      @color5,
      @color6,
      @color7,
      @color8,
      @color9,
      @color10,
      @color11,
      @color12,
      @color13, 
      @color14, 
      @color15
      */

  * {
      border: none;
      border-radius: 10px;
      font-family: Roboto, Helvetica, Arial, sans-serif;
      font-size: 13px;
      min-height: 0;
  }

  window#waybar {
      background-color: transparent;
      color: #ffffff;
      transition-property: background-color;
      transition-duration: .5s;
  }

  window#waybar.hidden {
      opacity: 0.2;
  }

  .modules-left {
      padding-left: 5px;
  }

  .modules-right {
      padding-right: 5px;
  }

  .modules-center {
      padding-right: 5px;
      padding-left: 5px;
  }


  #workspaces button {
      background: @background;
      color: #ffffff;
      border-radius: 20px;

  }

  /* https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect */
  #workspaces button:hover {
      background: @color13;
      color: @foreground;
      border-bottom: 0px solid #ffffff;
  }

  #workspaces button.focused {
      background: #ff0505;
  }

  #workspaces button.focused:hover {
      background: @color13;
      color: @foreground;
      border-bottom: 3px solid #ffffff;

  }

  #workspaces button.urgent {
      background-color: #eb4d4b;
  }

  #workspaces button.active {
      background-color: @cursor;
      color: @background;
  }

  #mode {
      background-color: #64727D;
      border-bottom: 3px solid #ffffff;
  }

  #clock,
  #battery,
  #cpu,
  #memory,
  #disk,
  #temperature,
  #backlight,
  #network,
  #pulseaudio,
  #custom-media,
  #custom-launcher,
  #custom-power,
  #custom-chatgpt,
  #custom-exalidraw,
  #custom-reboot,
  #custom-lock,
  #custom-quit,
  #custom-messages,
  #custom-calendar,
  #tray,
  #mode,
  #idle_inhibitor,

  #mpd {
      padding: 0 10px;
      color: @foreground;
  }

  #window,
  #workspaces {
      margin: 0px 4px;
  }

  /* If workspaces is the leftmost module, omit left margin */
  .modules-left>widget:first-child>#workspaces {
      margin-left: 0px;
  }

  /* If workspaces is the rightmost module, omit right margin */
  .modules-right>widget:last-child>#workspaces {
      margin-right: 0px;
  }

  #clock {
      background-image: linear-gradient(-45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #battery {
      background-color: @background;
      color: @foreground;
  }

  #battery.charging,
  #battery.plugged {
      color: #26A65B;
      background-color: @background;

  }

  @keyframes blink {
      to {
          background-color: #ffffff;
          color: #000000;
      }
  }

  #battery.critical:not(.charging) {
      background-color: #f53c3c;
      color: #ffffff;
      animation-name: blink;
      animation-duration: 0.5s;
      animation-timing-function: linear;
      animation-iteration-count: infinite;
      animation-direction: alternate;
  }

  label:focus {
      background-color: #000000;
  }

  #cpu {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #memory {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #disk {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #backlight {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);

  }

  #network {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #network.disconnected {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: red;
  }

  #bluetooth {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
      padding: 0px 10px;
  }


  #pulseaudio {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #pulseaudio.muted {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: red;
  }

  #custom-media {
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
      color: @foreground;
      border-radius: 20px;
      margin-right: 5px;
  }

  #custom-media.custom-spotify {
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
      color: @foreground;
      border-radius: 20px;
      margin-right: 5px;

  }

  #custom-media.custom-vlc {
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
      color: @foreground;
      border-radius: 20px;
      margin-right: 5px;
  }


  #custom-launcher {
      background-image: linear-gradient(-45deg, @color4 0%, @background 52%, @background 90%);
      font-size: 18px;
      border-radius: 20px;

  }

  #custom-updater {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #custom-chatgpt {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #custom-exalidraw {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #custom-messages {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #custom-calendar {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }


  #temperature {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #temperature.critical {
      background-color: #eb4d4b;
  }

  #tray {
      background-image: linear-gradient(-45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #tray>.passive {
      -gtk-icon-effect: dim;
      background-image: linear-gradient(-45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #tray>.needs-attention {
      -gtk-icon-effect: highlight;
      background-image: linear-gradient(-45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
  }

  #idle_inhibitor {
      background-image: linear-gradient(45deg, @color4 0%, @background 52%, @background 90%);
      border-radius: 20px 0px 0px 20px;

  }

  #idle_inhibitor.activated {
      background-image: linear-gradient(45deg, @color4 0%, @background 52%, @background 90%);
      color: @foreground;
      border-radius: 20px 0px 0px 20px;

  }

  #language {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
      min-width: 16px;
  }

  #keyboard-state {
      background: @background;
      color: @foreground;
      min-width: 16px;
  }

  #keyboard-state>label {
      padding: 0px 5px;
  }

  #keyboard-state>label.locked {
      background: rgba(0, 0, 0, 0.606);
  }

  .not-power {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      color: @foreground;
      /*padding: 10px 10px;*/
  }

  #custom-power {
      background-image: linear-gradient(45deg, @color4 0%, @background 52%, @color4 90%);
      font-size: 16px;
      border-radius: 19px;
  }

  #custom-quit {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      font-size: 16px;
      border-radius: 19px;
  }

  #custom-lock {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      font-size: 16px;
      border-radius: 19px;
  }

  #custom-reboot {
      background-image: linear-gradient(45deg, @background 0%, @background 52%, @background 90%);
      font-size: 16px;
      border-radius: 19px;
  }
''
