name: CI

on:
  push:
  pull_request:

jobs:
  build-server:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: "Maximize Disk Space"
        run: |
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /var/lib/docker/overlay2
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: "Install Cachix"
        uses: cachix/cachix-action@v15
        with:
          name: rickisnotmyrealname
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build NixOS Server
        run: nix build .#nixosConfigurations.NixOSServer.config.system.build.toplevel --accept-flake-config  
  build-desktop:
    runs-on: ubuntu-22.04
    needs: [build-server]
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: "Maximize Disk Space"
        run: |
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /var/lib/docker/overlay2
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: "Install Cachix"
        uses: cachix/cachix-action@v15
        with:
          name: rickisnotmyrealname
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build NixOS Desktop
        run: nix build .#nixosConfigurations.NixOSDesktop.config.system.build.toplevel --accept-flake-config

  build-laptop:
    runs-on: ubuntu-22.04
    needs: [build-desktop]
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: "Maximize Disk Space"
        run: |
          sudo rm -rf $AGENT_TOOLSDIRECTORY
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/heroku
          sudo rm -rf /var/lib/docker/overlay2
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /home/runner/.rustup
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: "Install Cachix"
        uses: cachix/cachix-action@v15
        with:
          name: rickisnotmyrealname
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build NixOS Laptop
        run: nix build .#nixosConfigurations.NixOSLaptop.config.system.build.toplevel --accept-flake-config
