# .github/workflows/build-systems.yml
# NixOSBaseContainer
# NixOSHomepageServer
# NixOSMinecraftServer
# NixOSWireguardServer
# NixOSTraefikServer
# NixOSAuthServer
# NixOSNextcloudServer
# NixOSServer
# NixOSLaptop
# NixOSDesktop
name: Combined Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-base_container:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSBaseContainer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-homepage-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSHomepageServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-minecraft-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSMinecraftServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-wireguard-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSWireguardServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-traefik-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSTraefikServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-auth-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSAuthServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-nextcloud-server:
    needs: build-base_container
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSNextcloudServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-server:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSServer.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-laptop:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSLaptop.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-desktop:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_command: |
        nix build .#nixosConfigurations.NixOSDesktop.config.system.build.toplevel --accept-flake-config
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
 
