name: CI

on:
  push:
  pull_request:

jobs:
  build-desktop:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build NixOS Desktop
        run: nix build .#nixosConfigurations.NixOSDesktop.config.system.build.toplevel --accept-flake-config

  build-laptop:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build NixOS Laptop
        run: nix build .#nixosConfigurations.NixOSLaptop.config.system.build.toplevel --accept-flake-config

  build-server:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build NixOS Server
        run: nix build .#nixosConfigurations.NixOSServer.config.system.build.toplevel --accept-flake-config
