# .github/workflows/reusable-build.yml
name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      build_command:
        description: 'The Nix build command to execute'
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: Build Component
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: Jayllyz/free-disk-space@refs/heads/perf/use-rmz
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install Cachix
        uses: cachix/cachix-action@v15
        with:
          name: rickisnotmyrealname
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Execute Build Command
        run: ${{ inputs.build_command }}
